export default {
    'Type something'                                    : 'Escreva algo...',

    // About
    'Advanced'                                          : 'Avançado',
    'About Jodit'                                       : 'Sobre Jodit',
    'Jodit Editor'                                      : 'Jodit Editor',
    'Free Non-commercial Version'                       : 'Versão grátis não comercial',
    'GNU General Public License, version 2 or later'    : 'GNU General Public License, Versão 2 ou posterior',
    'Jodit User\'s Guide'                               : 'Guia de usuario Jodit',
    'contains detailed help for using'                  : 'Contem ajuda detalhada para o uso.',
    'For information about the license, please go to our website:': 'Para informação sobre a licença, por favor visite nosso site:',
    'Buy full version'                                  : 'Compre a versão completa',
    'Copyright © XDSoft.net - Chupurnov Valeriy. All rights reserved.':
        'Copyright © XDSoft.net - Chupurnov Valeriy. Todos os direitos reservados.',

    // Toolbar
    'Anchor'                                            : 'Âncora',
    'Open in new tab'                                   : 'Abrir em nova aba',
    'Open editor in fullsize'                           : 'Abrir editor em tela inteira',
    'Clear Formatting'                                  : 'Limpar formatação',
    'Fill color or set the text color'                  : 'Cor de preenchimento ou letra',
    'Redo'                                              : 'Refazer',
    'Undo'                                              : 'Desfazer',
    'Bold'                                              : 'Negrito',
    'Italic'                                            : 'Itálico',
    'Insert Unordered List'                             : 'Inserir lista não ordenada',
    'Insert Ordered List'                               : 'Inserir lista ordenada',
    'Align Center'                                      : 'Alinhar no centro',
    'Align Justify'                                     : 'Alinhar Justificado',
    'Align Left'                                        : 'Alinhar à equerda',
    'Align Right'                                       : 'Alinhar à direita',
    'Insert Horizontal Line'                            : 'Inserir linha horizontal',
    'Insert Image'                                      : 'Inserir imagem',
    'Insert file'                                       : 'Inserir arquivo',
    'Insert youtube/vimeo video'                        : 'Inserir video do Youtube/vimeo',
    'Insert link'                                       : 'Inserir vínculo',
    'Font size'                                         : 'Tamanho da letra',
    'Font family'                                       : 'Familia de fonte',

    'Insert format block'                               : 'Inserir bloco',
    'Normal'                                            : 'Normal',
    'Heading 1'                                         : 'Cabeçalho 1',
    'Heading 2'                                         : 'Cabeçalho 2',
    'Heading 3'                                         : 'Cabeçalho 3',
    'Heading 4'                                         : 'Cabeçalho 4',
    'Quote'                                             : 'Citação',
    'Code'                                              : 'Código',

    'Insert'                                            : 'Inserir',
    'Insert table'                                      : 'Inserir tabela',

    'Decrease Indent'                                   : 'Diminuir identação',
    'Increase Indent'                                   : 'Aumentar identação',
    'Select Special Character'                          : 'Selecionar caracter especial',
    'Insert Special Character'                          : 'Inserir caracter especial',

    'Paint format'                                      : 'Copiar formato',
    'Change mode'                                       : 'Trocar modo',

    //plugin Image
    'Margins'                                           : 'Margens',
    'top'                                               : 'Acima',
    'right'                                             : 'Direita',
    'bottom'                                            : 'Abaixo',
    'left'                                              : 'Esquerda',
    'Styles'                                            : 'Estilos CSS',
    'Classes'                                           : 'Classes CSS',
    'Align'                                             : 'Alinhar',
    'Right'                                             : 'Direita',
    'Center'                                            : 'Centro',
    'Left'                                              : 'Esquerda',
    '--Not Set--'                                       : '--Não estabelecido--',
    'Src'                                               : 'Fonte',
    'Title'                                             : 'Título',
    'Alternative'                                       : 'Texto Alternativo',
    'Link'                                              : 'Link',
    'Open link in new tab'                              : 'Abrir Link em nova aba',
    'Image'                                             : 'Imagem',
    'file'                                              : 'Arquivo',
    'Advansed'                                          : 'Avançado',
    'Image properties'                                  : 'Propiedades de imagem',
    'Cancel'                                            : 'Cancelar',
    'Ok'                                                : 'Ok',

    //plugin paste
    'Your code is similar to HTML. Keep as HTML?'       : 'O código é parecido a HTML. Matenr como HTML?',
    'Paste as HTML'                                     : 'Colar como HTML?',
    'Keep'                                              : 'Manter',
    'Clean'                                             : 'Limpar',
    'Insert as Text'                                    : 'Inserir como texto',
    'Word Paste Detected'                               : 'Colagem do Word detectada',

    'The pasted content is coming from a Microsoft Word/Excel document. Do you want to keep the format or clean it up?':
        'O conteudo colado vem de um documento de Microsoft Word/Excel. Deseja manter o formato ou limpá-lo?',

    'Insert only Text'                                  : 'Inserir somente o texto',

    // File Browser module
    'File Browser'                                      : 'Buscar arquivo',
    'Error on load list'                                : 'Error ao carregar a lista',
    'Error on load folders'                             : 'Error al carregar as pastas',
    'Are you sure?'                                     : 'Tem certeza?',
    'Enter Directory name'                              : 'Coloque o nome da pasta',
    'Create directory'                                  : 'Criar pasta',
    'type name'                                         : 'Coloque o nome',


    // Form module
    'Drop image'                                        : 'Soltar imagem',
    'Drop file'                                         : 'Soltar arquivo',
    'or click'                                          : 'ou clique',
    'Alternative text'                                  : 'Texto alternativo',
    'Browse'                                            : 'Buscar',
    'Upload'                                            : 'Upload',
    'Background'                                        : 'Fundo',
    'Text'                                              : 'Texto',

    // popap module
    'Top'                                               : 'Acima',
    'Middle'                                            : 'Centro',
    'Bottom'                                            : 'Abaixo',
    'Insert column before'                              : 'Inserir coluna antes',
    'Insert column after'                               : 'Inserir coluna depois',
    'Insert row above'                                  : 'Inserir linha acima',
    'Insert row below'                                  : 'Inserir linha abaixo',
    'Delete table'                                      : 'Apagar tabela',
    'Delete row'                                        : 'Apagar linha',
    'Delete column'                                     : 'Apagar coluna',
    'Empty cell'                                        : 'Limpar célula',

    'Delete'                                            : 'Apagar',
    'Strike through'                                    : 'Riscado',
    'Underline'                                         : 'Sublinhado',
    'Break'                                             : 'Quebra',
    'Search for'                                        : 'Buscar por',
    'Replace with'                                      : 'Substituir por',
    'Replace'                                           : 'Substituir',
    'Edit'                                              : 'Editar',
    'Vertical align'                                    : 'Alinhamento vertical',
    'Horizontal align'                                  : 'Alinhamento horizontal',
    'Filter'                                            : 'filtrar',
    'Sort by changed'                                   : 'Ordenar por data de modificação',
    'Sort by name'                                      : 'Ordenar por nome',
    'Sort by size'                                      : 'Ordenar por tamanho',
    'Add folder'                                        : 'Adicionar pasta',
    'Split vertical'                                    : 'Dividir vertical',
    'Split horizontal'                                  : 'Dividir horizontal',
    'Merge'                                             : 'Mesclar',
    'Add column'                                        : 'Adicionar coluna',
    'Add row'                                           : 'Adocionar linha',
    'Border'                                            : 'Borda',
    'Embed code'                                        : 'Incluir código',
    'Update'                                            : 'Atualizar',
    'superscript'                                       : 'superindice',
    'subscript'                                         : 'subindice',
    'Cut selection'                                     : 'Cortar seleção',
    'Paste'                                             : 'Colar',
    'Choose Content to Paste'                           : 'Selecionar conteúdo para colar',


    // stat
    'Chars: %d': 'Caractéres: %d',
    'Words: %d': 'Palavras: %d',

    'All': 'Tudo',
    'Select %s': 'Selecionar: %s',
    'Select all': 'Selecionar tudo',

    'source': 'fonte',
    'bold': 'negrito',
    'italic': 'itálico',
    'brush': 'pincel',
    'link': 'link',
    'undo': 'desfazer',
    'redo': 'refazer',
    'table': 'tabela',
    'image': 'Imagem',
    'eraser': 'Borracha',
    'paragraph': 'Parágrafo',
    'fontsize': 'Tamanho da letra',
    'video': 'vídeo',
    'font': 'fonte',
    'about': 'sobre',
    'print': 'imprimir',
    'symbol': 'simbolo',
    'underline': 'sublinhado',
    'strikethrough': 'riscar',
    'indent': 'identação',
    'outdent': 'tirar identação',
    'fullsize': 'tela inteira',
    'shrink': 'diminuir',
    'copyformat': 'Copiar formato',
    'hr': 'linha horizontal',
    'ul': 'lista desordenar',
    'ol': 'lista ordenada',
    'cut': 'Cortar',
    'selectall': 'Selecionar tudo',
    'Open link': 'Abrir link',
    'Edit link': 'Editar link',
    'No follow': 'Não seguir',
    'Unlink': 'Desvincular',
    ' URL': 'URL',
    'Reset': 'Resetar',
    'Save': 'Salvar',
    'Save as ...': 'Salvar como...',
    'Resize': 'Redimensionar',
    'Crop': 'Recortar',
    'Width': 'Largura',
    'Height': 'Altura',
    'Keep Aspect Ratio': 'Manter proporção',
    'Yes': 'Sim',
    'No': 'No',
    'Remove': 'Remover',
    'Select': 'Selecionar',
    'You can only edit your own images. Download this image on the host?': 'Você so pode editar suas próprias imagens. Baixar esta imagem no computador?',
    'The image has been successfully uploaded to the host!': 'A imagem foi enviada com sucesso ao servidor!',

};
